In [17]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df = pd.read_csv('movies.csv')
df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [18]:
df = df[['title', 'genres', 'movieId']]
df =df.fillna('')
df.head()

,title,genres,movieId
0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1
1,Jumanji (1995),Adventure|Children|Fantasy,2
2,Grumpier Old Men (1995),Comedy|Romance,3
3,Waiting to Exhale (1995),Comedy|Drama|Romance,4
4,Father of the Bride Part II (1995),Comedy,5

In [20]:
df['features'] = df['title'] + ' ' + df['genres'] + ' ' + df['movieId'].astype(str)

In [23]:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()